//! Errors that can be generated by H.263 operations

use std::io::Error as IoError;
use thiserror::Error;

#[derive(Debug, Error)]
pub enum Error {
    #[error("the H.263 decoder failed internally, this is a bug")]
    InternalDecoderError,

    #[error("the H.263 bitstream could not be decoded")]
    InvalidBitstream,

    #[error("an I/O error occured: {0}")]
    UnhandledIoError(IoError),
}

impl From<IoError> for Error {
    fn from(ioe: IoError) -> Self {
        Error::UnhandledIoError(ioe)
    }
}

pub type Result<T> = std::result::Result<T, Error>;
